# Used by goreleaser: the binary is prebuilt and copied in.
FROM alpine:3 AS certs
RUN apk add --no-cache ca-certificates

FROM scratch
COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY send2kindle /send2kindle
USER 1000:1000
ENTRYPOINT ["/send2kindle"]
